### ISSUE TITLE
Missing a bin entry

### ISSUE THREAD

**Issue by jeffijoe** [jogaram/tsc-glob#1]
To run `tsc-glob` from a run-script, you need to add a `bin` entry in `package.json`.

Example:

```
  "bin": {
    "tsc-glob": "./bin/tsc-glob.js"
  },
```

**Comment by draco1989** [comment]
I pushed an update of the repo right now. Fixing this and the executable.

It seems that the executable file had CRLF line breaks and linux does not like it...
